# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'motor_encoder_assembly_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_motor_encoder_assembly_test(object):
    def setupUi(self, motor_encoder_assembly_test):
        motor_encoder_assembly_test.setObjectName("motor_encoder_assembly_test")
        motor_encoder_assembly_test.resize(436, 141)
        self.centralwidget = QtWidgets.QWidget(motor_encoder_assembly_test)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 411, 100))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.encoder_ticks = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.encoder_ticks.setObjectName("encoder_ticks")
        self.gridLayout.addWidget(self.encoder_ticks, 0, 1, 1, 1)
        self.motor_cmd = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.motor_cmd.setObjectName("motor_cmd")
        self.gridLayout.addWidget(self.motor_cmd, 2, 2, 1, 1)
        self.encoder_deg = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.encoder_deg.setObjectName("encoder_deg")
        self.gridLayout.addWidget(self.encoder_deg, 0, 2, 1, 1)
        self.motor_cmd_slider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.motor_cmd_slider.setMinimum(-1000)
        self.motor_cmd_slider.setMaximum(1000)
        self.motor_cmd_slider.setOrientation(QtCore.Qt.Horizontal)
        self.motor_cmd_slider.setObjectName("motor_cmd_slider")
        self.gridLayout.addWidget(self.motor_cmd_slider, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.encoder_rpm = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.encoder_rpm.setObjectName("encoder_rpm")
        self.gridLayout.addWidget(self.encoder_rpm, 1, 1, 1, 1)
        self.encoder_rps = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.encoder_rps.setObjectName("encoder_rps")
        self.gridLayout.addWidget(self.encoder_rps, 1, 2, 1, 1)
        self.gridLayout.setColumnMinimumWidth(2, 150)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.motor_stop = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.motor_stop.setObjectName("motor_stop")
        self.horizontalLayout.addWidget(self.motor_stop)
        self.verticalLayout.addLayout(self.horizontalLayout)
        motor_encoder_assembly_test.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(motor_encoder_assembly_test)
        self.statusbar.setObjectName("statusbar")
        motor_encoder_assembly_test.setStatusBar(self.statusbar)

        self.retranslateUi(motor_encoder_assembly_test)
        QtCore.QMetaObject.connectSlotsByName(motor_encoder_assembly_test)

    def retranslateUi(self, motor_encoder_assembly_test):
        _translate = QtCore.QCoreApplication.translate
        motor_encoder_assembly_test.setWindowTitle(_translate("motor_encoder_assembly_test", "motor_encoder_assembly_test"))
        self.encoder_ticks.setText(_translate("motor_encoder_assembly_test", "0 Ticks"))
        self.motor_cmd.setText(_translate("motor_encoder_assembly_test", "0.0"))
        self.encoder_deg.setText(_translate("motor_encoder_assembly_test", "0 Deg"))
        self.label_3.setText(_translate("motor_encoder_assembly_test", "Motor (cmd):"))
        self.label.setText(_translate("motor_encoder_assembly_test", "Theta:"))
        self.label_2.setText(_translate("motor_encoder_assembly_test", "W:"))
        self.encoder_rpm.setText(_translate("motor_encoder_assembly_test", "0 RPM"))
        self.encoder_rps.setText(_translate("motor_encoder_assembly_test", "0 Rad/s"))
        self.motor_stop.setText(_translate("motor_encoder_assembly_test", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    motor_encoder_assembly_test = QtWidgets.QMainWindow()
    ui = Ui_motor_encoder_assembly_test()
    ui.setupUi(motor_encoder_assembly_test)
    motor_encoder_assembly_test.show()
    sys.exit(app.exec_())
