name: Publish Mobot App to Playstore
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./android
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build Project
        run: ./gradlew build

      - name: Build Release Bundle
        run: ./gradlew bundleRelease

      - name: Sign Bundle
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGN_KEY }}
          alias: key0
          keyStorePassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Publish to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{secrets.PUBLISH_MOBOT_APP_SERVICE_ACCOUNT}}
          packageName: io.github.mobotx
          releaseFiles: android/app/build/outputs/bundle/release/app-release.aab
          whatsNewDirectory: android/whatsnew
